<?php
define('ROOT', dirname(dirname(__FILE__)));
require_once(ROOT . '/Head.phtml');
?>
<script type="text/javascript" src="/skin/javascript.js"></script>
</head>
<?php
$data_Array = $model->getAddressData();
$rows = count($data_Array);
$cols = count($data_Array, COUNT_RECURSIVE)/$rows;
//print_r($data_Array);
?>

<body>
<div class="row">
    <article class="row">
    <?php if ($data_Array['id'] != ''): ?>
        <header>
            <h1><?php echo $data_Array['prefix']; ?>&nbsp;<?php echo $data_Array['prename']; ?>&nbsp;<?php echo $data_Array['name']; ?>, ID <?php echo $data_Array['id']; ?></h1>
        </header>
        <section class="content" id="address">
            <article class="col-2 left-col">
                <section class="col-content" id="contact">
                    <table id="person">
                        <colgroup width="200"></colgroup>
                        <tr>
                            <td>Anrede</td>
                            <td><?php echo $data_Array['prefix']; ?>&nbsp;<?php echo $data_Array['prename']; ?>&nbsp;<?php echo $data_Array['name']; ?></td>
                        </tr>
                        <tr>
                            <td>Adresse</td>
                            <td><?php echo $data_Array['street']; ?>&nbsp;<?php if ($data_Array['nr'] != '0') { echo $data_Array['nr']; } ?></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><?php if ($data_Array['zipcode'] != '0') { echo $data_Array['zipcode']; } ?>&nbsp;<?php echo $data_Array['city']; ?></td>
                        </tr>
                        <tr>
                            <td>Geburtsdatum</td>
                            <td>
                                <?php if ($data_Array['date_birth'] != '0000-00-00'): ?>
                                <?php echo $model->changeDate2German($data_Array['date_birth']); ?>
                                <?php endif ?>
                            </td>
                        </tr>
                        <tr>
                            <td>E-Mail</td>
                            <td><?php echo $data_Array['mail']; ?></td>
                        </tr>
                        <tr>
                            <td>Festnetz</td>
                            <td><?php echo $data_Array['phone']; ?></td>
                        </tr>
                        <tr>
                            <td>Handy</td>
                            <td><?php echo $data_Array['mobile']; ?></td>
                        </tr>
                    </table>
                </section>
            </article>
            <article class="col-2 right-col">
                <section class="col-content buttons" id="buttons">
                    <form name="update" action="/application/Controller/AddressesController.php" method="post">
                        <p>
                            <input name="cancel" type="button" value="Hauptmenü" onclick="window.location.href = '../../../index.phtml';" >
                            <input type="hidden" name="id" value="<?php echo $data_Array['id']; ?>"/>
                            <input type="hidden" name="prename" value="<?php echo $data_Array['prename']; ?>"/>
                            <input type="hidden" name="name" value="<?php echo $data_Array['name']; ?>"/>
                            <button type="submit" name="action" value="edit">Bewerber bearbeiten</button>
                        </p>
                    </form>
                </section>
            </article>
        </section>
    <?php else : ?>
        <section class="error" id="error">
            <header>
                <h1 class="error">Bewerber nicht gefunden!</h1>
            </header>
            <section class="col-content buttons" id="buttons">
                <form name="error" >
                    <p><input name="cancel" type="button" value="Hauptmenü " onclick="window.location.href = '../../../index.phtml';" ></p>
                </form>
            </section>
        <section>
    <?php endif ?>
    </article>
</div>
</body>
</head>