    <?php
    define('ROOT', dirname(dirname(__FILE__)));
    require_once(ROOT . '/Head.phtml');
    ?>
    <script type="text/javascript" src="/js/db.js"></script>
</head>
    <?php
    $edit = false;
    $dataArray = $model->getAddressData();
    if (isset($dataArray))
    {
//        print_r($data_Array);
        $edit = true;
    }
    ?>
<body>
    <div class="main-container">
    <header class="main-header"></header>
    <?php if (!$edit || $dataArray['id'] != ''): ?>
        <div class="main-content wrapper ">
            <div class="row">
                <section class="row">
                    <article class="mod-account mod-content mod-login col-6">
                    <?php if ($edit) : ?>
                        <header class="sub-header">
                            <h1>bearbeiten</h1>
                        </header>
                    <?php else : ?>
                        <header class="sub-header">
                            <h1>hinzufügen</h1>
                        </header>
                    <?php endif ?>
                        <div class="row">
                                <!--<form name="new" action="../Controller/AddressesController.php" method="post" onsubmit="return chkAppForm ()" onreset="return resetChk()">-->
                            <form name="new" action="/Application/Controller/AddressesController.php" method="post" >
                                <article class="mod content col-3 push-right">
                                    <fieldset id="contact">
                                        <div class="form-item required clearfix">
                                            <label for="name">Name</label>
                                            <p class="input">
                                                <input type="text" id="name" class="input input-text required-entry" title="Name"
                                                       name="name" maxlength="255" value="<?php if ($edit) { echo $dataArray['name']; } ?>">
                                            </p>
                                        </div>
                                        <div class="form-item required clearfix">
                                            <label for="prename">Vorname</label>
                                            <p class="input">
                                                <input type="text" id="prename" class="input input-text required-entry" title="Vorname"
                                                       name="prename" maxlength="255" value="<?php if ($edit) { echo $dataArray['prename']; } ?>">
                                            </p>
                                        </div>
                                        <div class="form-item clearfix">
                                            <label for="date-birth">Geburtsdatum</label>
                                            <p class="input">
                                                <input type="text" id="date-birth" class="input input-text" title="Geburtsdatum"
                                                       name="date_birth" maxlength="10" value="<?php if ($edit && $dataArray['date_birth'] != '0000-00-00') { echo $model->changeDate2German($dataArray['date_birth']); } ?>">
                                            </p>
                                        </div>
                                        <div class="form-item clearfix">
                                            <label for="street">Strasse, Nr</label>
                                            <p class="input">
                                                <input type="text" id="street" class="input input-text left-text" title="Strasse" name="street"
                                                       maxlength="255" value="<?php if ($edit) { echo $dataArray['street']; } ?>">
                                                <input type="text" id="nr" class="input input-text right-text" title="Hausnummer" name="nr"
                                                       maxlength="6" value="<?php if ($edit && $dataArray['nr'] != '0') { echo $dataArray['nr']; } ?>">
                                            </p>
                                        </div>
                                        <div class="form-item clearfix">
                                            <label for="city">PLZ, Ort</label>
                                            <p class="input">
                                                <input type="text" id="zipcode" class="input input-text left-text" title="Postleitzahl" name="zipcode"
                                                       maxlength="5" value="<?php if ($edit && $dataArray['zipcode']) { echo $dataArray['zipcode']; } ?>">
                                                <input type="text" id="city" class="input input-text right-text" title="Stadt" name="city"
                                                       maxlength="255" value="<?php if ($edit) { echo $dataArray['city']; } ?>">
                                            </p>
                                        </div>
                                        <div class="form-item required clearfix">
                                            <label for="mail">E-Mail</label>
                                            <p class="input">
                                                <input type="text" id="mail" class="input input-text required-entry" title="E-Mail-Adresse"
                                                       name="mail" maxlength="255" value="<?php if ($edit) { echo $dataArray['mail']; } ?>">
                                            </p>
                                        </div>
                                        <div class="form-item">
                                            <label for="phone">Telefonnummer (040-123456)</label>
                                            <p class="input">
                                                <input type="text" id="phone" class="input input-text" title="Telefonnummer" name="phone"
                                                       maxlength="32" value="<?php if ($edit) { echo $dataArray['phone']; } ?>">
                                            </p>
                                        </div>
                                    </fieldset>
                                    <fieldset id="buttons">
                                        <div class="form-submit clearfix">
                                            <p>
                                                <input name="cancel" type="button" value="Abbrechen " onclick="window.location.href = '../../../index.phtml';" >
                                                <?php if (!$edit): ?>
                                                    <input name="reset" type="reset" value="Zurücksetzen">
                                                <?php endif ?>
                                                <button type="submit" name="action" value="<?php if ($edit) { echo 'update'; } else { echo 'save'; } ?>"><?php if ($edit) { echo 'Aktualisieren'; } else { echo 'Speichern'; } ?></button>
                                            </p>
                                        </div>
                                    </fieldset>
                                </article>
                            </form>
                        </div>
                    </article>
                </section>
            </div>
        </div>
    <?php else : ?>
        <div class="main-content wrapper ">
            <div class="row">
                <section class="row">
                    <article class="mod-account mod-content mod-login mod-error col-6">
                        <header>
                            <h1 class="error">Bewerber nicht gefunden!</h1>
                        </header>
                        <div class="row push-bottom buttons">
                            <form name="error" >
                                <p><input name="cancel" type="button" value="Hauptmenü " onclick="window.location.href = '../../../index.phtml';" ></p>
                            </form>
                        </div>
                    </article>
                </section>
            </div>
        </div>
    <?php endif ?>
    </div>
</body>
